root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "task build"
  full_bin = "task run"
  exclude_regex = ["_test.go"]
  include_dir = ["cmd", "pkg", "views"]
  include_ext = ["go", "templ", "css"]
  stop_on_error = true