# https://taskfile.dev

version: '3'

method: timestamp

vars:
  APP_NAME: todo

tasks:

  default:
    cmds:
      - task: run

  run:
    aliases: [r]
    deps: [build]
    cmds:
      - ./tmp/{{.APP_NAME}}

  build:
    sources:
      - views/**/*.templ
      - views/**/*.go
      - cmd/**/*.go
      - pkg/**/*.go
      - views/static/**
    generates:
      - ./tmp/todo
    cmds:
      - "echo building commit: {{.GIT_COMMIT}}"
      - go mod tidy
      - task: gen-html
      - go build -ldflags="-X main.version=dev" -o=./tmp/{{.APP_NAME}} ./cmd/web
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h

  build-prod:
    cmds:
      - task: gen-all
      - task: ci
      - go build -ldflags="-extldflags=-static -X main.version=1.0.0" -o=./{{.APP_NAME}} ./cmd/web
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h

  ci:
    deps: [audit, test]
    cmds:
      - task: static-check

  tools:
    desc: "Install CLI tools"
    aliases: [deps]
    cmds:
      - go install github.com/air-verse/air@latest
      - go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - go get -tool github.com/rakyll/gotest@latest
      - go get -tool honnef.co/go/tools/cmd/staticcheck@latest
      - go get -tool github.com/stephenafamo/bob/gen/bobgen-sqlite@latest
      - go get -tool github.com/a-h/templ/cmd/templ@latest

  audit:
    cmds:
      - go mod tidy
      - go mod verify
      - go fmt ./...

  static-check:
    cmds:
      - go vet ./...
      - go tool staticcheck ./cmd/...

  test:
    aliases: [t]
    cmds:
      - go tool gotest ./...

  gen-all:
    cmds:
      - task: gen-sql
      - task: gen-html

  gen-sql:
    deps: [db-migrate-up]
    cmds:
      - go tool bobgen-sqlite -c bobgen.yaml

  gen-html:
    cmds:
      - templ generate
      - templ fmt .

  db:
    cmds:
      - "sqlite3 -box ./tmp/{{.APP_NAME}}.db"

  db-migrate-new:
    desc: "Generates a new migration file"
    requires:
      vars: [NAME]
    cmds:
      - migrate create -seq -ext=.sql -dir=./database/migrations/sqlite {{.NAME}}

  db-migrate-up:
    cmds:
      - task: db-migrate
        vars:
          OP: up

  db-migrate-down:
    cmds:
      - task: db-migrate
        vars:
          OP: down

  db-migrate-force:
    requires:
      vars: [VERSION]
    cmds:
      - task: db-migrate
        vars:
          OP: force {{.VERSION}}

  db-migrate:
    internal: true
    cmds:
      - migrate -path "./database/migrations/sqlite" -database "sqlite3://./tmp/{{.APP_NAME}}.db" {{.OP}}
